reviewers:
  defaults:
    - code-owners
  groups:
    code-owners:
      - Ferret-san
      - distractedm1nd
files:
  '**':
    - code-owners
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 1
